variables:
  IMAGE_VERSION: "0.1"

stages:
  - build
  - deploy

build:
  image: node:latest
  stage: build
  script:
    - npm i
    - npm run build
  artifacts:
    paths:
      - build/

pages:
  image: alpine:latest
  stage: deploy
  variables:
    GIT_STRATEGY: none # Do not clone git repo
  script:
    - mv build public
  artifacts:
    paths:
      - public


express:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" docker.io
    - docker pull mauromazzocchetti/webtorrent-web-gui-standalone:latest
    - docker build --progress=plain --tag="mauromazzocchetti/webtorrent-web-gui-standalone:$IMAGE_VERSION" --tag="mauromazzocchetti/webtorrent-web-gui-standalone:latest" ./
    - docker push mauromazzocchetti/webtorrent-web-gui-standalone:$IMAGE_VERSION
    - docker push mauromazzocchetti/webtorrent-web-gui-standalone:latest
    - docker logout
